"""rename address

Revision ID: 047cb8e24300
Revises: 51cb4b40517a
Create Date: 2026-01-22 08:29:05.598864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047cb8e24300'
down_revision = '51cb4b40517a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
